# Generated by Django 5.2 on 2025-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_add_time',
            field=models.FloatField(default=0.0),
        ),
    ]
